# Generated by Django 5.2.4 on 2025-08-12 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('sprint_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('test_area', models.CharField(max_length=255)),
                ('test_scenario', models.TextField()),
                ('status', models.CharField(choices=[('PASSED', 'PASSED'), ('NOT_EXECUTED', 'NOT EXECUTED'), ('FAILED', 'FAILED')], default='NOT_EXECUTED', max_length=20)),
                ('retest_status', models.CharField(choices=[('PASSED', 'PASSED'), ('NOT_EXECUTED', 'NOT EXECUTED'), ('FAILED', 'FAILED')], default='NOT_EXECUTED', max_length=20)),
                ('actual_evidence', models.URLField(blank=True, max_length=500)),
                ('bug_link', models.URLField(blank=True, max_length=500)),
                ('sprint', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL)),
                ('approved_by_dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.developer')),
                ('approved_by_PM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.productmanager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.task')),
            ],
        ),
    ]
