# Generated by Django 5.2.4 on 2025-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
